/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package br.com.fornax.thalyta.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import br.com.fornax.thalyta.type.TipoType;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-01-18T18:39:32.283Z")

@Validated
@Api(value = "seguro", description = "the seguro API")
@RequestMapping(value = "/v1")
public interface SeguroApi {

    @ApiOperation(value = "Atualizar seguro", nickname = "atualizarSeguro", notes = "Atualizar seguro no banco de dados", response = TipoType.class, tags={ "seguro", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = TipoType.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Segurado not found") })
    @RequestMapping(value = "/seguro",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<TipoType> atualizarSeguro(@ApiParam(value = "" ,required=true )  @Valid @RequestBody TipoType body);


    @ApiOperation(value = "Consultar seguro", nickname = "consultarSeguro", notes = "Consultar segurado por proposta", response = TipoType.class, responseContainer = "List", tags={ "seguro", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = TipoType.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Seguro not found") })
    @RequestMapping(value = "/seguro/{proposta}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<TipoType> consultarSeguro(@ApiParam(value = "Porposta do seguro",required=true) @PathVariable("proposta") Integer proposta);


    @ApiOperation(value = "Deletar seguro", nickname = "deletarSeguro", notes = "Deletar seguro por cpf", response = TipoType.class, tags={ "seguro", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = TipoType.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Segurado not found") })
    @RequestMapping(value = "/seguro",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.DELETE)
    ResponseEntity<TipoType> deletarSeguro(@ApiParam(value = "cpf do segurado" ,required=true) @RequestHeader(value="proposta", required=true) Integer proposta);


    @ApiOperation(value = "Salvar seguro", nickname = "salvarSeguro", notes = "Salvar seguro no banco de dados", response = TipoType.class, responseContainer = "List", tags={ "seguro", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = TipoType.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Seguro not found") })
    @RequestMapping(value = "/seguro",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<TipoType> salvarSeguro(@ApiParam(value = ""  )  @Valid @RequestBody TipoType body);

}
